name: sirene
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.2.6
  cloud_firestore: ^4.14.0
  dio: ^5.4.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  latlong2: ^0.9.0
  open_route_service: ^1.2.3
  permission_handler: ^11.1.0
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
      - assets/svg/